---
# Cluster connection (from sandbox)
ocp4_workload_ocpsandbox_argocd_user_openshift_api_url: "{{ sandbox_openshift_api_url }}"
ocp4_workload_ocpsandbox_argocd_user_openshift_api_token: "{{ cluster_admin_agnosticd_sa_token }}"

# User to create AppProject for -- defaults to userX-GUID format
ocp4_workload_ocpsandbox_argocd_user_username: "user1-{{ guid }}"

# ArgoCD configuration
ocp4_workload_ocpsandbox_argocd_user_namespace: openshift-gitops
ocp4_workload_ocpsandbox_argocd_user_project_prefix: "appproject-"
ocp4_workload_ocpsandbox_argocd_user_cluster_resource_whitelist: []
# Example:
# - group: ""
#   kind: Namespace
