---
- name: Configure tenant OpenShift GitOps access
  module_defaults:
    group/kubernetes.core.k8s:
      host: "{{ ocp4_workload_tenant_openshift_gitops_openshift_api_url }}"
      api_key: "{{ ocp4_workload_tenant_openshift_gitops_openshift_api_token }}"
      validate_certs: false
  block:
  - name: Create tenant AppProject for {{ ocp4_workload_tenant_openshift_gitops_user }}
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', 'appproject-user.yaml.j2') }}"

  - name: Add user account to ArgoCD CR
    kubernetes.core.k8s:
      api_version: argoproj.io/v1beta1
      kind: ArgoCD
      namespace: "{{ ocp4_workload_tenant_openshift_gitops_namespace }}"
      name: openshift-gitops
      state: patched
      definition:
        spec:
          extraConfig: "{{ {'accounts.' ~ ocp4_workload_tenant_openshift_gitops_user: 'apiKey, login'} }}"

  - name: Generate HTPasswd hash for password
    ansible.builtin.shell: |
      htpasswd -nbBC 10 "" "{{ ocp4_workload_tenant_openshift_gitops_user_password }}" | tr -d ':\n'
    register: r_htpasswd_hash
    no_log: true

  - name: Set password for {{ ocp4_workload_tenant_openshift_gitops_user }} in argocd-secret
    kubernetes.core.k8s_json_patch:
      api_version: v1
      kind: Secret
      name: argocd-secret
      namespace: "{{ ocp4_workload_tenant_openshift_gitops_namespace }}"
      patch:
      - op: add
        path: /data/accounts.{{ ocp4_workload_tenant_openshift_gitops_user }}.password
        value: "{{ r_htpasswd_hash.stdout | b64encode }}"
    no_log: true

  - name: Get the OpenShift GitOps ArgoCD server route
    kubernetes.core.k8s_info:
      api_version: route.openshift.io/v1
      kind: Route
      name: "{{ ocp4_workload_tenant_openshift_gitops_argocd_cr_name }}-server"
      namespace: "{{ ocp4_workload_tenant_openshift_gitops_namespace }}"
    register: r_openshift_gitops_server_route

  - name: Set ArgoCD URL fact
    ansible.builtin.set_fact:
      _ocp4_workload_tenant_openshift_gitops_url: "https://{{ r_openshift_gitops_server_route.resources[0].spec.host }}"

  # yamllint disable rule:line-length
  - name: Save AgnosticD user data
    agnosticd.core.agnosticd_user_info:
      msg: "OpenShift GitOps AppProject created: {{ ocp4_workload_tenant_openshift_gitops_user_project_prefix }}-{{ ocp4_workload_tenant_openshift_gitops_user }}"
      data:
        openshift_gitops_server: "{{ _ocp4_workload_tenant_openshift_gitops_url }}"
        openshift_gitops_user: "{{ ocp4_workload_tenant_openshift_gitops_user }}"
        openshift_gitops_password: "{{ ocp4_workload_tenant_openshift_gitops_user_password }}"
        openshift_gitops_appproject: "{{ ocp4_workload_tenant_openshift_gitops_user_project_prefix }}-{{ ocp4_workload_tenant_openshift_gitops_user }}"
  # yamllint enable rule:line-length
