---
- name: Remove config on cluster as cluster admin
  module_defaults:
    group/k8s:
      host: "{{ sandbox_openshift_api_url }}"
      api_key: "{{ cluster_admin_agnosticd_sa_token }}"
      validate_certs: false
  block:
  - name: Remove devworkspace
    vars:
      _ns_private_lmaas_namespace_devspaces: "{{ ns_private_lmaas_namespace_devspaces }}-{{ guid }}"
    kubernetes.core.k8s:
      state: absent
      template: devworkspace.yaml.j2
    
  - name: Remove rolebindings
    vars:
      _ns_private_lmaas_namespace: "{{ namespace_prefix }}-{{ guid }}"
    kubernetes.core.k8s:
      state: absent
      template: rolebinding.yaml.j2
    loop: "{{ ns_private_lmaas_namespace_prefixes }}"
    loop_control:
      loop_var: namespace_prefix

  - name: Remove namespaces
    kubernetes.core.k8s:
      state: absent
      api_version: v1
      kind: Namespace
      name: "{{ namespace_prefix }}-{{ guid }}"
    loop: "{{ ns_private_lmaas_namespace_prefixes }}"
    loop_control:
      loop_var: namespace_prefix
