---
- name: The following variables are available
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
  - "sandbox_openshift_api_key:              {{ sandbox_openshift_api_key }}"
  - "sandbox_openshift_api_token:            {{ sandbox_openshift_api_token }}"
  - "sandbox_openshift_api_url:              {{ sandbox_openshift_api_url }}"
  - "sandbox_openshift_apps_domain:          {{ sandbox_openshift_apps_domain }}"
  - "sandbox_openshift_cluster:              {{ sandbox_openshift_cluster }}"
  - "sandbox_openshift_console_url:          {{ sandbox_openshift_console_url }}"
  - "sandbox_openshift_credentials:          {{ sandbox_openshift_credentials }}"
  - "sandbox_openshift_name:                 {{ sandbox_openshift_name }}"
  - "sandbox_openshift_namespace:            {{ sandbox_openshift_namespace }}"
  - "sandbox_openshift_password:             {{ sandbox_openshift_password }}"
  - "sandbox_openshift_user:                 {{ sandbox_openshift_user }}"
  - "cluster_admin_agnosticd_sa_token:       {{ cluster_admin_agnosticd_sa_token | default('Not available') }}"

- name: Save AgnosticD user data
  agnosticd.core.agnosticd_user_info:
    data:
      sandbox_openshift_namespace: "{{ sandbox_openshift_namespace }}"
      sandbox_openshift_user: "{{ sandbox_openshift_user }}"
      sandbox_openshift_password: "{{ sandbox_openshift_password }}"
      sandbox_openshift_api_token: "{{ sandbox_openshift_api_token }}"
      sandbox_openshift_api_url: "{{ sandbox_openshift_api_url }}"
      sandbox_openshift_console_url: "{{ sandbox_openshift_console_url }}"
      sandbox_openshift_apps_domain: "{{ sandbox_openshift_apps_domain }}"

- name: Set up config on cluster as cluster admin
  environment:
    K8S_AUTH_HOST: "{{ sandbox_openshift_api_url }}"
    K8S_AUTH_API_KEY: "{{ cluster_admin_agnosticd_sa_token }}"
    K8S_AUTH_VERIFY_SSL: false
  # module_defaults:
  #   group/k8s:
  #     host: "{{ sandbox_openshift_api_url }}"
  #     api_key: "{{ cluster_admin_agnosticd_sa_token }}"
  #     validate_certs: false
  block:
  - name: Create namespaces
    vars:
      _ns_private_lmaas_namespace: "{{ namespace_prefix }}-{{ guid }}"
    kubernetes.core.k8s:
      state: present
      template: namespace.yaml.j2
    loop: "{{ ns_private_lmaas_namespace_prefixes }}"
    loop_control:
      loop_var: namespace_prefix

  - name: Create rolebindings
    vars:
      _ns_private_lmaas_namespace: "{{ namespace_prefix }}-{{ guid }}"
    kubernetes.core.k8s:
      state: present
      template: rolebinding.yaml.j2
    loop: "{{ ns_private_lmaas_namespace_prefixes }}"
    loop_control:
      loop_var: namespace_prefix

  - name: Create devworkspace
    vars:
      _ns_private_lmaas_namespace_devspaces: "{{ ns_private_lmaas_namespace_devspaces }}-{{ guid }}"
    kubernetes.core.k8s:
      state: present
      template: devworkspace.yaml.j2
