---
- name: Remove DevSpaces resources
  module_defaults:
    group/kubernetes.core.k8s:
      host: "{{ ocp4_workload_tenant_devspaces_openshift_api_url }}"
      api_key: "{{ ocp4_workload_tenant_devspaces_openshift_api_token }}"
      validate_certs: false
  block:
    - name: Delete DevWorkspace
      kubernetes.core.k8s:
        state: absent
        api_version: workspace.devfile.io/v1alpha2
        kind: DevWorkspace
        name: "{{ ocp4_workload_tenant_devspaces_devworkspace_name }}"
        namespace: "{{ ocp4_workload_tenant_devspaces_namespace }}"
      ignore_errors: true

    - name: Delete DevWorkspaceTemplate (if exists)
      kubernetes.core.k8s:
        state: absent
        api_version: workspace.devfile.io/v1alpha2
        kind: DevWorkspaceTemplate
        name: "{{ ocp4_workload_tenant_devspaces_devworkspace_template_name }}"
        namespace: "{{ ocp4_workload_tenant_devspaces_namespace }}"
      ignore_errors: true

    - name: Delete environment variables ConfigMap (if exists)
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: ConfigMap
        name: devworkspace-env
        namespace: "{{ ocp4_workload_tenant_devspaces_namespace }}"
      ignore_errors: true
