---
galaxy_info:
  author: AgnosticD Team
  description: Create a tenant user on a shared GitLab instance
  company: Red Hat
  license: GPL-3.0-only
  min_ansible_version: "2.15"
  galaxy_tags:
  - gitlab
  - tenant
  - git

dependencies: []
