---
# ------------------------------------------
# Implement your workload removal tasks here
# ------------------------------------------

- name: Deprovision your workload
  ansible.builtin.debug:
    msg: "Nothing to deprovision for example workload."
