---
- name: Get Gitea custom resource
  kubernetes.core.k8s_info:
    host: "{{ ocp4_workload_tenant_gitea_user_openshift_api_url }}"
    api_key: "{{ ocp4_workload_tenant_gitea_user_openshift_api_token }}"
    validate_certs: false
    api_version: pfe.rhpds.com/v1
    kind: Gitea
    name: "{{ ocp4_workload_tenant_gitea_user_instance }}"
    namespace: "{{ ocp4_workload_tenant_gitea_user_namespace }}"
  register: r_gitea
  failed_when: r_gitea.resources | length == 0

- name: Validate Gitea admin setup is complete
  ansible.builtin.assert:
    that:
    - r_gitea.resources[0].status.adminSetupComplete | bool
    fail_msg: Gitea admin setup is not complete yet.

- name: Set Gitea connection facts
  ansible.builtin.set_fact:
    _ocp4_workload_tenant_gitea_user_admin_user: >-
      {{ r_gitea.resources[0].spec.giteaAdminUser }}
    _ocp4_workload_tenant_gitea_user_admin_password: >-
      {{ r_gitea.resources[0].status.adminPassword }}
    _ocp4_workload_tenant_gitea_user_route: >-
      {{ r_gitea.resources[0].status.giteaRoute }}

- name: Check if Gitea user exists
  ansible.builtin.uri:
    url: >-
      {{ _ocp4_workload_tenant_gitea_user_route }}/api/v1/users/{{ ocp4_workload_tenant_gitea_user_username }}
    method: GET
    url_username: "{{ _ocp4_workload_tenant_gitea_user_admin_user }}"
    url_password: "{{ _ocp4_workload_tenant_gitea_user_admin_password }}"
    force_basic_auth: true
    validate_certs: false
    status_code:
    - 200
    - 404
  register: r_gitea_user

- name: Create Gitea user
  when: r_gitea_user.status == 404
  ansible.builtin.uri:
    url: "{{ _ocp4_workload_tenant_gitea_user_route }}/api/v1/admin/users"
    method: POST
    url_username: "{{ _ocp4_workload_tenant_gitea_user_admin_user }}"
    url_password: "{{ _ocp4_workload_tenant_gitea_user_admin_password }}"
    force_basic_auth: true
    body_format: json
    body:
      email: "{{ ocp4_workload_tenant_gitea_user_email }}"
      login_name: "{{ ocp4_workload_tenant_gitea_user_username }}"
      must_change_password: false
      password: "{{ ocp4_workload_tenant_gitea_user_password }}"
      username: "{{ ocp4_workload_tenant_gitea_user_username }}"
    validate_certs: false
    status_code:
    - 201

- name: Migrate repositories
  when: ocp4_workload_tenant_gitea_user_repositories | length > 0
  block:
  - name: Get Gitea user uid
    ansible.builtin.uri:
      url: >-
        {{ _ocp4_workload_tenant_gitea_user_route }}/api/v1/users/{{ ocp4_workload_tenant_gitea_user_username }}
      method: GET
      url_username: "{{ _ocp4_workload_tenant_gitea_user_admin_user }}"
      url_password: "{{ _ocp4_workload_tenant_gitea_user_admin_password }}"
      force_basic_auth: true
      validate_certs: false
    register: r_gitea_user_info

  - name: Check if repositories already exist
    ansible.builtin.uri:
      url: >-
        {{ _ocp4_workload_tenant_gitea_user_route }}/api/v1/repos/{{
        ocp4_workload_tenant_gitea_user_username }}/{{ item.name }}
      method: GET
      url_username: "{{ _ocp4_workload_tenant_gitea_user_admin_user }}"
      url_password: "{{ _ocp4_workload_tenant_gitea_user_admin_password }}"
      force_basic_auth: true
      validate_certs: false
      status_code:
      - 200
      - 404
    register: r_gitea_repos
    loop: "{{ ocp4_workload_tenant_gitea_user_repositories }}"
    loop_control:
      label: "{{ item.name }}"

  - name: Migrate repositories that do not exist yet
    when: item.status == 404
    ansible.builtin.uri:
      url: "{{ _ocp4_workload_tenant_gitea_user_route }}/api/v1/repos/migrate"
      method: POST
      url_username: "{{ _ocp4_workload_tenant_gitea_user_admin_user }}"
      url_password: "{{ _ocp4_workload_tenant_gitea_user_admin_password }}"
      force_basic_auth: true
      body_format: json
      body: >-
        {{
          {
            'clone_addr': item.item.repo,
            'description': '',
            'issues': false,
            'milestones': false,
            'mirror': false,
            'private': item.item.private | default(false),
            'repo_name': item.item.name,
            'uid': r_gitea_user_info.json.id | int
          }
        }}
      validate_certs: false
      status_code:
      - 201
      timeout: 60
    register: r_migrate_result
    until: r_migrate_result.status == 201
    retries: 24
    delay: 5
    loop: "{{ r_gitea_repos.results }}"
    loop_control:
      label: "{{ item.item.name }}"

- name: Save Gitea user information
  agnosticd.core.agnosticd_user_info:
    data:
      gitea_url: "{{ _ocp4_workload_tenant_gitea_user_route }}"
      gitea_username: "{{ ocp4_workload_tenant_gitea_user_username }}"
      gitea_password: "{{ ocp4_workload_tenant_gitea_user_password }}"
