---
# Cluster connection (from sandbox)
ocp4_workload_ocpsandbox_gitea_user_openshift_api_url: "{{ sandbox_openshift_api_url }}"
ocp4_workload_ocpsandbox_gitea_user_openshift_api_token: "{{ cluster_admin_agnosticd_sa_token }}"

# User to create -- defaults to userX-GUID format
ocp4_workload_ocpsandbox_gitea_user_username: "user1-{{ guid }}"
ocp4_workload_ocpsandbox_gitea_user_password: ""

# Gitea configuration
ocp4_workload_ocpsandbox_gitea_user_namespace: gitea
ocp4_workload_ocpsandbox_gitea_user_admin_user: ""
ocp4_workload_ocpsandbox_gitea_user_admin_password: ""

# Repositories to migrate for the user
ocp4_workload_ocpsandbox_gitea_user_repositories: []
# Example:
# - name: mcp
#   repo: https://github.com/rhpds/mcp-gitops
#   private: false
