---
- name: Set up cluster access and discover cluster info
  ansible.builtin.include_tasks: setup_kubeconfig.yml

- name: Create Keycloak user
  ansible.builtin.include_tasks: create_keycloak_user.yml

- name: Save user information
  agnosticd.core.agnosticd_user_info:
    data:
      user: "{{ ocp4_workload_tenant_keycloak_user_username }}"
      password: "{{ ocp4_workload_tenant_keycloak_user_password }}"
      openshift_api_url: "{{ ocp4_workload_tenant_keycloak_user_openshift_api_url }}"
      openshift_console_url: "{{ _ocp4_workload_tenant_keycloak_user_console_url }}"
      openshift_cluster_ingress_domain: "{{ _ocp4_workload_tenant_keycloak_user_ingress_domain }}"
