---
- name: Create ArgoCD AppProject for user
  kubernetes.core.k8s:
    host: "{{ ocp4_workload_ocpsandbox_argocd_user_openshift_api_url }}"
    api_key: "{{ ocp4_workload_ocpsandbox_argocd_user_openshift_api_token }}"
    validate_certs: false
    state: present
    template: appproject-user.yaml.j2

- name: Save ArgoCD information
  agnosticd.core.agnosticd_user_info:
    data:
      argocd_project: "{{ ocp4_workload_ocpsandbox_argocd_user_project_prefix }}{{ ocp4_workload_ocpsandbox_argocd_user_username }}"
